package ipp.w7x.neutralBeams;


import ipp.neutralBeams.SimpleBeamGeometry;
import algorithmrepository.Algorithms;
import fusionOptics.Util;
import fusionOptics.interfaces.NullInterface;
import fusionOptics.surfaces.Cylinder;
import fusionOptics.types.Optic;

/** Simple static beam line info for use in the ray tracer 
 * Generated by minerva-neutralBeams/src/seed.minerva.neutralBeams.w7x.DumpBeamLines
 * */
public abstract class W7xNBI extends SimpleBeamGeometry {
	
	/* upper/lower = real hall Z
	 * near/away = near/away from the other beam box, or AEA21
	 * 
	 * Q1 is upper, away 
	 * Q2 is upper, nearer
	 * Q3 is lower, nearer
	 * Q4 is lower, away
	 *   
	 * Q5 is lower, nearer
	 * Q6 is lower, away
	 * Q7 is upper, away
	 * Q8 is upper, nearer
	 */
	
	/* --------------------------
	w7xBeamDefs  */
	static {
		nbiStart = new double[][]{
				{3.480123, 5.144472, -0.305}, 
				{3.415672, 5.175421, -0.305}, 
				{3.415672, 5.175421, -0.305}, 
				{3.480123, 5.144472, -0.305}, 
				{0.2787, 6.194685, 0.305}, 
				{0.208366, 6.20753, 0.305}, 
				{0.208366, 6.20753, 0.305}, 
				{0.2787, 6.194685, 0.305}, 
			};
		nbiUnit = new double[][]{
				{-0.365971, -0.926698, 0.085417}, 
				{-0.494403, -0.865026, 0.085417}, 
				{-0.494403, -0.865026, -0.085417}, 
				{-0.365971, -0.926698, -0.085417}, 
				{-0.108469, -0.990423, -0.085417}, 
				{-0.248623, -0.964827, -0.085417}, 
				{-0.248623, -0.964827, 0.085417}, 
				{-0.108469, -0.990423, 0.085417}, 
			};
	}		

	
}
