package ipp.w7x.neutralBeams;


import ipp.neutralBeams.SimpleBeamGeometry;
import algorithmrepository.Algorithms;
import fusionOptics.Util;
import fusionOptics.interfaces.NullInterface;
import fusionOptics.surfaces.Cylinder;
import fusionOptics.types.Optic;

/** Simple static beam line info for use in the ray tracer 
 * Generated by minerva-neutralBeams/src/seed.minerva.neutralBeams.DumpBeamLines
 * */
public abstract class W7XRudix extends SimpleBeamGeometry {
	
	static {
		nbiStart = new double[][]{
				{-2.963, -5.648, -0.165}, 
			};
		nbiUnit = new double[][]{
				{0.501398, 0.806289, 0.313845}, 
			};
	}
		
}
