package ipp.w7x.neutralBeams;


import algorithmrepository.Algorithms;
import fusionDefs.neutralBeams.SimpleBeamGeometry;
import fusionOptics.Util;
import fusionOptics.interfaces.NullInterface;
import fusionOptics.surfaces.Cylinder;
import fusionOptics.types.Optic;

/** Simple static beam line info for use in the ray tracer 
 * Generated by minerva-neutralBeams/src/seed.minerva.neutralBeams.DumpBeamLines
 * */
public class W7XRudix extends SimpleBeamGeometry {
	
	private static W7XRudix instance = new W7XRudix();
	
	/** The default as-advertised geometry */
	public static W7XRudix def(){ return instance;	}
	
	private double Px[][];
	private double u[][];
	
	public W7XRudix() {
	
		Px = new double[][]{
				{-2.963, -5.648, -0.165}, 
			};
		u = new double[][]{
				{0.501398, 0.806289, 0.313845}, 
			};
		
		beamWidth = 0.16; //Made up
		sourceR = 8.00; //Made up
		plasmaR0 = 5.0; //Made up
		plasmaR1 = 6.5; //Made up
	}

	@Override
	public double[][] startAll() { return Px; }
	@Override
	public double[][] uVecAll() { return u; }

	@Override
	public double[] startBox(int boxIdx) { return Px[0]; }

	@Override
	public double[] uVecBox(int boxIdx) { return u[0]; }

	@Override
	public double[] getVoltageAll() { return new double[]{ Double.NaN }; } // No idea what this will be
}
